import type { FraudRule } from '../models';

export const MOCK_RULES: FraudRule[] = [
  { code: 'RF-01', titulo: 'Pérdida total por robo (PTxRB)', descripcion: 'La cobertura "Pérdida Total por Robo" en vehículos activa esta regla crítica.', clasificacion: 'rojo', kind: 'critica', maxPts: 14, activaciones30d: 9, enabled: true },
  { code: 'RF-02', titulo: 'Documento posiblemente alterado', descripcion: 'Documentos con fechas inconsistentes, sellos sospechosos o ediciones evidentes.', clasificacion: 'rojo', kind: 'critica', maxPts: 14, activaciones30d: 3, enabled: true },
  { code: 'RF-03', titulo: 'Coincidencia con lista restrictiva', descripcion: 'Asegurado, beneficiario o proveedor figura en la lista interna de actores observados.', clasificacion: 'rojo', kind: 'critica', maxPts: 10, activaciones30d: 14, enabled: true },
  { code: 'RF-04', titulo: 'Dinámica del accidente inconsistente', descripcion: 'El relato del siniestro contradice la evidencia física (croquis, daños, parte policial).', clasificacion: 'rojo', kind: 'critica', maxPts: 12, activaciones30d: 7, enabled: true },
  { code: 'RF-05', titulo: 'Siniestro al borde de vigencia', descripcion: 'Evento ocurrido en las primeras 48 horas o las últimas 48 horas de vigencia de la póliza.', clasificacion: 'amarillo', kind: 'amarilla', maxPts: 8, activaciones30d: 8, enabled: true },
  { code: 'RF-06', titulo: 'Demora atípica en denuncia', descripcion: 'Diferencia >4 días entre el evento reportado y la denuncia formal en fiscalía.', clasificacion: 'amarillo', kind: 'amarilla', maxPts: 8, activaciones30d: 11, enabled: true },
  { code: 'RF-07', titulo: 'Narrativa similar (>85%)', descripcion: 'Similitud textual con otro siniestro previo por encima del umbral de NLP.', clasificacion: 'amarillo', kind: 'amarilla', maxPts: 8, activaciones30d: 6, enabled: true },
  { code: 'FS-01', titulo: 'Reclamo cerca del borde de póliza', descripcion: 'Ocurrencia ≤10 días: 8 pts · 11-30 días: 4 pts · >30: 0.', clasificacion: 'amarillo', kind: 'scored', maxPts: 8, activaciones30d: 12, enabled: true },
  { code: 'FS-02', titulo: 'Demora de denuncia (robo)', descripcion: '>48 h: 8 pts · 24-48 h: 4 pts · <24 h: 0.', clasificacion: 'amarillo', kind: 'scored', maxPts: 8, activaciones30d: 7, enabled: true },
  { code: 'FS-03', titulo: 'Frecuencia del asegurado', descripcion: '≥3 reclamos en 18 meses: 8 pts · 2: 4 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 8, activaciones30d: 11, enabled: true },
  { code: 'FS-04', titulo: 'Frecuencia del vehículo', descripcion: 'Mismo vehículo con múltiples siniestros en 18 meses.', clasificacion: 'amarillo', kind: 'scored', maxPts: 6, activaciones30d: 4, enabled: true },
  { code: 'FS-05', titulo: 'Frecuencia del conductor', descripcion: 'Mismo conductor con múltiples eventos en 18 meses.', clasificacion: 'amarillo', kind: 'scored', maxPts: 8, activaciones30d: 5, enabled: true },
  { code: 'FS-06', titulo: 'Alta frecuencia RC', descripcion: '>2 eventos previos solo de Responsabilidad Civil: 6 pts · 1: 3 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 6, activaciones30d: 9, enabled: true },
  { code: 'FS-07', titulo: 'Beneficiario / proveedor recurrente', descripcion: 'Lista restrictiva: 10 pts · >2 observado: 5 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 10, activaciones30d: 14, enabled: true },
  { code: 'FS-08', titulo: 'Documentos legales incompletos', descripcion: 'Faltan piezas obligatorias (denuncia fiscal, acta policial, endosos).', clasificacion: 'verde', kind: 'scored', maxPts: 4, activaciones30d: 18, enabled: true },
  { code: 'FS-09', titulo: 'Dinámica sospechosa', descripcion: 'Narrativa ilógica: 6 pts · evento múltiple en madrugada: 3 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 6, activaciones30d: 6, enabled: true },
  { code: 'FS-10', titulo: 'Daño severo sin tercero', descripcion: 'Daños altos sin testigos, cámaras ni partes oficiales.', clasificacion: 'amarillo', kind: 'scored', maxPts: 6, activaciones30d: 5, enabled: true },
  { code: 'FS-11', titulo: 'Documentos inconsistentes', descripcion: 'Alteraciones confirmadas o fechas anteriores al evento.', clasificacion: 'rojo', kind: 'scored', maxPts: 10, activaciones30d: 4, enabled: true },
  { code: 'FS-12', titulo: 'Reporte tardío', descripcion: '>7 días: 5 pts · 4-7 días: 3 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 5, activaciones30d: 9, enabled: true },
  { code: 'FS-13', titulo: 'Narrativas similares (NLP)', descripcion: 'Similitud >85%: 8 pts · 70-84%: 4 pts.', clasificacion: 'amarillo', kind: 'scored', maxPts: 8, activaciones30d: 8, enabled: true },
  { code: 'FS-14', titulo: 'Monto cerca de suma asegurada', descripcion: 'Reclamo >95% de la suma o >50% del promedio del taller.', clasificacion: 'amarillo', kind: 'scored', maxPts: 5, activaciones30d: 7, enabled: false },
];
