import { riskTier } from '../../../shared/utils';
import type { Claim } from '../models';

const RAW: Omit<Claim, 'nivel' | 'review'>[] = [
  {
    id: 'SIN-2026-08412',
    ramo: 'vehiculos',
    cobertura: 'Pérdida total por robo',
    asegurado: 'María F. Salazar T.',
    asegurado_id: 'ASG-23981',
    poliza: 'PV-7782341',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-04-18',
    fecha_reporte: '2026-05-03',
    monto_reclamado: 38500,
    suma_asegurada: 42000,
    estado: 'Reserva',
    sucursal: 'Quito Norte',
    vehiculo: {
      marca: 'Toyota',
      modelo: 'Fortuner',
      anio: 2023,
      placa: 'PCH-4821',
      chasis: 'MR0HZ8CD4...',
    },
    proveedor: 'PRV-0142',
    descripcion:
      'Vehículo reportado robado en sector La Carolina. Asegurado indica que el vehículo fue sustraído mientras se encontraba estacionado frente a su domicilio durante la noche. No se cuenta con denuncia inmediata; la denuncia fiscal fue presentada 12 días después del evento.',
    score: 91,
    alertas: [
      {
        code: 'RF01',
        puntos: 14,
        severidad: 'high',
        detalle: 'Cobertura pérdida total por robo activa regla crítica RF01.',
      },
      {
        code: 'RF06',
        puntos: 8,
        severidad: 'high',
        detalle: '12 días entre ocurrencia y denuncia formal (> 4 días).',
      },
      {
        code: 'RF03',
        puntos: 10,
        severidad: 'high',
        detalle: 'Taller asignado (PRV-0142) coincide con lista restrictiva interna.',
      },
      {
        code: 'RF05',
        puntos: 4,
        severidad: 'med',
        detalle: 'Siniestro a 21 días del inicio de vigencia.',
      },
      {
        code: 'AF02',
        puntos: 4,
        severidad: 'med',
        detalle: 'Falta acta policial original y certificado de propiedad endosado.',
      },
    ],
    timeline: [
      { date: '2026-03-28', title: 'Inicio de vigencia de póliza', tone: 'ok' },
      {
        date: '2026-04-18',
        title: 'Ocurrencia reportada por asegurado',
        tone: 'warn',
        desc: 'Robo nocturno sin testigos ni cámaras.',
      },
      {
        date: '2026-04-30',
        title: 'Denuncia fiscal presentada',
        tone: 'danger',
        desc: '12 días después del evento reportado.',
      },
      { date: '2026-05-03', title: 'Reporte de siniestro a aseguradora', tone: 'warn' },
      {
        date: '2026-05-08',
        title: 'Asignación a taller PRV-0142',
        tone: 'danger',
        desc: 'Proveedor en lista restrictiva.',
      },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Denuncia fiscal', estado: 'Presentada con demora' },
      { tipo: 'Acta policial', estado: 'Faltante', falta: true },
      { tipo: 'Matrícula del vehículo', estado: 'Completo' },
      { tipo: 'Certificado de endoso', estado: 'Faltante', falta: true },
    ],
    ml_probability: 0.83,
    ml_factors: [
      { feature: 'demora_denuncia_horas', shap_value: 0.642, direction: 'up' },
      { feature: 'dias_desde_inicio_poliza', shap_value: 0.418, direction: 'up' },
      { feature: 'proveedor_en_lista_restrictiva', shap_value: 0.295, direction: 'up' },
    ],
    anomaly_score: -0.682,
    nearest_normal_claim_id: 'SIN-2026-08376',
    similar: [
      {
        claim_id: 'SIN-2025-07344',
        similarity: 0.91,
        snippet:
          'Vehículo reportado robado en sector residencial. Denuncia presentada después de varios días sin testigos.',
      },
      {
        claim_id: 'SIN-2025-06911',
        similarity: 0.83,
        snippet:
          'Robo nocturno del vehículo estacionado, sin cámaras de seguridad y denuncia tardía.',
      },
    ],
  },
  {
    id: 'SIN-2026-08398',
    ramo: 'vehiculos',
    cobertura: 'Choque - daños materiales',
    asegurado: 'Roberto A. Andrade M.',
    asegurado_id: 'ASG-19402',
    poliza: 'PV-6624112',
    ciudad: 'Guayaquil',
    fecha_ocurrencia: '2026-04-26',
    fecha_reporte: '2026-04-27',
    monto_reclamado: 9870,
    suma_asegurada: 28000,
    estado: 'Pago Parcial',
    sucursal: 'Guayaquil Centro',
    vehiculo: {
      marca: 'Chevrolet',
      modelo: 'Sail',
      anio: 2021,
      placa: 'GAB-1947',
      chasis: '9BGSC19...',
    },
    proveedor: 'PRV-0317',
    descripcion:
      'Asegurado reporta colisión frontal contra muro de contención en vía perimetral. El relato describe pérdida de control por neblina densa. Sin tercero involucrado, sin testigos. Tercer evento del asegurado en 14 meses con narrativa similar.',
    score: 87,
    alertas: [
      {
        code: 'RF07',
        puntos: 8,
        severidad: 'high',
        detalle: '92% de similitud textual con SIN-2025-07112.',
      },
      {
        code: 'AF01',
        puntos: 8,
        severidad: 'high',
        detalle: 'Asegurado con 3 siniestros en 14 meses.',
      },
      {
        code: 'RF04',
        puntos: 6,
        severidad: 'med',
        detalle: 'Daño localizado inconsistente con dinámica descrita.',
      },
      {
        code: 'AF05',
        puntos: 5,
        severidad: 'med',
        detalle: 'Daño severo sin tercero, sin cámaras y sin partes oficiales.',
      },
    ],
    timeline: [
      { date: '2025-01-15', title: 'Inicio de vigencia de póliza', tone: 'ok' },
      {
        date: '2025-02-22',
        title: 'Primer siniestro (SIN-2025-07112)',
        tone: 'warn',
        desc: 'Narrativa similar - choque sin tercero.',
      },
      { date: '2025-11-09', title: 'Segundo siniestro (SIN-2025-07955)', tone: 'warn' },
      { date: '2026-04-26', title: 'Tercer evento - el actual', tone: 'danger' },
      { date: '2026-04-27', title: 'Reporte de siniestro', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Parte policial', estado: 'Faltante', falta: true },
      { tipo: 'Fotografías del daño', estado: 'Completo' },
      { tipo: 'Proforma del taller', estado: 'Completo' },
    ],
    ml_probability: 0.76,
    ml_factors: [
      { feature: 'narrativa_similar_score', shap_value: 0.541, direction: 'up' },
      { feature: 'historial_siniestros_asegurado', shap_value: 0.387, direction: 'up' },
      { feature: 'sin_rastro_tercero', shap_value: 0.213, direction: 'up' },
    ],
    anomaly_score: -0.412,
    nearest_normal_claim_id: 'SIN-2026-08321',
    similar: [
      {
        claim_id: 'SIN-2025-07112',
        similarity: 0.92,
        snippet:
          'Colisión frontal contra muro en vía perimetral, pérdida de control sin tercero ni testigos.',
      },
      {
        claim_id: 'SIN-2025-07955',
        similarity: 0.78,
        snippet: 'Daño material sin tercero involucrado, narrativa de neblina densa en vía rápida.',
      },
    ],
  },
  {
    id: 'SIN-2026-08376',
    ramo: 'salud',
    cobertura: 'Atención hospitalaria',
    asegurado: 'Carlos E. Vega Morales',
    asegurado_id: 'ASG-30221',
    poliza: 'PS-3398716',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-04-22',
    fecha_reporte: '2026-04-22',
    monto_reclamado: 2840,
    suma_asegurada: 25000,
    estado: 'Liquidado',
    sucursal: 'Quito Norte',
    proveedor: 'PRV-0078',
    descripcion:
      'Atención hospitalaria por apendicectomía de emergencia. Documentación clínica completa, factura emitida por proveedor con histórico limpio.',
    score: 12,
    alertas: [],
    timeline: [
      { date: '2025-09-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-04-22', title: 'Atención médica de emergencia', tone: 'ok' },
      { date: '2026-04-22', title: 'Reporte y autorización', tone: 'ok' },
      { date: '2026-04-30', title: 'Liquidación completa', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Epicrisis', estado: 'Completo' },
      { tipo: 'Factura del prestador', estado: 'Completo' },
      { tipo: 'Historia clínica', estado: 'Completo' },
      { tipo: 'Autorización previa', estado: 'Completo' },
    ],
    ml_probability: 0.08,
    ml_factors: [
      { feature: 'monto_reclamado', shap_value: -0.184, direction: 'down' },
      { feature: 'dias_entre_ocurrencia_reporte', shap_value: -0.142, direction: 'down' },
      { feature: 'documentos_incompletos', shap_value: -0.091, direction: 'down' },
    ],
    anomaly_score: -0.118,
    nearest_normal_claim_id: 'SIN-2026-08321',
    similar: [],
  },
  {
    id: 'SIN-2026-08365',
    ramo: 'vehiculos',
    cobertura: 'Volcadura',
    asegurado: 'Pamela G. Torres L.',
    asegurado_id: 'ASG-44219',
    poliza: 'PV-8849022',
    ciudad: 'Ambato',
    fecha_ocurrencia: '2026-04-15',
    fecha_reporte: '2026-04-19',
    monto_reclamado: 14200,
    suma_asegurada: 22000,
    estado: 'Reserva',
    sucursal: 'Ambato',
    vehiculo: {
      marca: 'Hyundai',
      modelo: 'Tucson',
      anio: 2020,
      placa: 'TBA-0319',
      chasis: 'KMHJ381...',
    },
    proveedor: 'PRV-0623',
    descripcion:
      'Volcadura en carretera Ambato-Baños durante la madrugada. La descripción y croquis del relato presentan inconsistencias menores con la dinámica reportada en parte policial.',
    score: 64,
    alertas: [
      {
        code: 'RF04',
        puntos: 6,
        severidad: 'med',
        detalle: 'Accidente múltiple de madrugada (3 a.m.).',
      },
      {
        code: 'AF03',
        puntos: 3,
        severidad: 'med',
        detalle: 'Reporte 4 días después de la ocurrencia.',
      },
      {
        code: 'AF02',
        puntos: 4,
        severidad: 'low',
        detalle: 'Falta certificado médico del conductor.',
      },
      {
        code: 'RF07',
        puntos: 4,
        severidad: 'med',
        detalle: '71% de similitud textual con SIN-2025-06882.',
      },
    ],
    timeline: [
      { date: '2025-11-20', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-04-15', title: 'Volcadura - 3:14 a.m.', tone: 'warn' },
      { date: '2026-04-19', title: 'Reporte de siniestro', tone: 'warn' },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Parte policial', estado: 'Completo' },
      { tipo: 'Certificado médico', estado: 'Faltante', falta: true },
      { tipo: 'Fotografías del daño', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08354',
    ramo: 'vehiculos',
    cobertura: 'Robo total',
    asegurado: 'Diego F. Paredes V.',
    asegurado_id: 'ASG-50012',
    poliza: 'PV-9012883',
    ciudad: 'Guayaquil',
    fecha_ocurrencia: '2026-04-08',
    fecha_reporte: '2026-04-09',
    monto_reclamado: 26900,
    suma_asegurada: 28000,
    estado: 'Reserva',
    sucursal: 'Guayaquil Norte',
    vehiculo: {
      marca: 'Kia',
      modelo: 'Sportage',
      anio: 2022,
      placa: 'GSA-7720',
      chasis: 'KNAPC81...',
    },
    proveedor: 'PRV-0089',
    descripcion:
      'Robo de vehículo a 9 días del inicio de vigencia. Asegurado contrató cobertura amplia 9 días antes del evento. Pago de prima al contado.',
    score: 78,
    alertas: [
      { code: 'RF01', puntos: 14, severidad: 'high', detalle: 'Cobertura pérdida total por robo.' },
      {
        code: 'RF05',
        puntos: 8,
        severidad: 'high',
        detalle: 'Siniestro a 9 días del inicio de vigencia (≤ 10 días).',
      },
      {
        code: 'AF04',
        puntos: 5,
        severidad: 'med',
        detalle: 'Reclamo representa el 96% de la suma asegurada.',
      },
    ],
    timeline: [
      { date: '2026-03-30', title: 'Contratación de póliza con cobertura amplia', tone: 'warn' },
      {
        date: '2026-04-08',
        title: 'Robo reportado',
        tone: 'danger',
        desc: '9 días después de contratada.',
      },
      { date: '2026-04-09', title: 'Denuncia y reporte', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Denuncia fiscal', estado: 'Completo' },
      { tipo: 'Acta policial', estado: 'Completo' },
      { tipo: 'Matrícula', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08321',
    ramo: 'hogar',
    cobertura: 'Daño por agua',
    asegurado: 'Lucía A. Bermeo F.',
    asegurado_id: 'ASG-11283',
    poliza: 'PH-4471299',
    ciudad: 'Cuenca',
    fecha_ocurrencia: '2026-04-12',
    fecha_reporte: '2026-04-13',
    monto_reclamado: 1820,
    suma_asegurada: 12000,
    estado: 'Liquidado',
    sucursal: 'Cuenca',
    proveedor: null,
    descripcion:
      'Daño por filtración de agua desde apartamento superior. Documentación completa, evaluación pericial concuerda con monto.',
    score: 18,
    alertas: [
      {
        code: 'AF02',
        puntos: 2,
        severidad: 'low',
        detalle: 'Falta certificación del administrador del edificio.',
      },
    ],
    timeline: [
      { date: '2025-06-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-04-12', title: 'Filtración detectada', tone: 'ok' },
      { date: '2026-04-13', title: 'Reporte de siniestro', tone: 'ok' },
      { date: '2026-04-26', title: 'Liquidación', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Informe pericial', estado: 'Completo' },
      { tipo: 'Fotografías', estado: 'Completo' },
      { tipo: 'Certificación administrador', estado: 'Faltante', falta: true },
    ],
  },
  {
    id: 'SIN-2026-08299',
    ramo: 'vehiculos',
    cobertura: 'Choque frontal',
    asegurado: 'Andrés R. Cárdenas P.',
    asegurado_id: 'ASG-78002',
    poliza: 'PV-3318873',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-04-02',
    fecha_reporte: '2026-04-09',
    monto_reclamado: 5400,
    suma_asegurada: 19500,
    estado: 'Reserva',
    sucursal: 'Quito Sur',
    vehiculo: { marca: 'Mazda', modelo: 'CX-5', anio: 2019, placa: 'PDD-8821' },
    proveedor: 'PRV-0317',
    descripcion:
      'Colisión frontal en intersección. Documentación incompleta y reporte 7 días después del evento.',
    score: 58,
    alertas: [
      { code: 'AF03', puntos: 5, severidad: 'med', detalle: 'Reporte tardío - 7 días después.' },
      { code: 'AF02', puntos: 4, severidad: 'med', detalle: 'Faltan dos documentos legales.' },
      {
        code: 'RF04',
        puntos: 6,
        severidad: 'med',
        detalle: 'Posicionamiento de daños no concuerda con croquis.',
      },
    ],
    timeline: [
      { date: '2025-08-15', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-04-02', title: 'Ocurrencia', tone: 'ok' },
      {
        date: '2026-04-09',
        title: 'Reporte tardío',
        tone: 'warn',
        desc: '7 días después del evento.',
      },
    ],
    documentos: [
      { tipo: 'Solicitud de siniestro', estado: 'Completo' },
      { tipo: 'Parte policial', estado: 'Faltante', falta: true },
      { tipo: 'Proforma taller', estado: 'Faltante', falta: true },
      { tipo: 'Fotografías', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08281',
    ramo: 'salud',
    cobertura: 'Cirugía ambulatoria',
    asegurado: 'Sofía M. Naranjo G.',
    asegurado_id: 'ASG-22091',
    poliza: 'PS-9981277',
    ciudad: 'Guayaquil',
    fecha_ocurrencia: '2026-03-29',
    fecha_reporte: '2026-03-29',
    monto_reclamado: 3950,
    suma_asegurada: 25000,
    estado: 'Liquidado',
    sucursal: 'Guayaquil Centro',
    proveedor: 'PRV-0089',
    descripcion:
      'Cirugía ambulatoria de rodilla. Cuarto reclamo en 11 meses con el mismo proveedor.',
    score: 53,
    alertas: [
      {
        code: 'AF01',
        puntos: 8,
        severidad: 'med',
        detalle: '4 reclamos en 11 meses con mismo proveedor.',
      },
      {
        code: 'AF04',
        puntos: 3,
        severidad: 'low',
        detalle: 'Monto 16% superior al promedio de la cobertura.',
      },
    ],
    timeline: [
      { date: '2025-06-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2025-08-12', title: 'Reclamo previo (consulta)', tone: 'warn' },
      { date: '2025-12-04', title: 'Reclamo previo (terapia)', tone: 'warn' },
      { date: '2026-02-18', title: 'Reclamo previo (estudios)', tone: 'warn' },
      { date: '2026-03-29', title: 'Cirugía ambulatoria - actual', tone: 'warn' },
    ],
    documentos: [
      { tipo: 'Epicrisis', estado: 'Completo' },
      { tipo: 'Factura', estado: 'Completo' },
      { tipo: 'Autorización previa', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08254',
    ramo: 'vehiculos',
    cobertura: 'Responsabilidad civil',
    asegurado: 'Javier S. Mora R.',
    asegurado_id: 'ASG-66112',
    poliza: 'PV-1129921',
    ciudad: 'Loja',
    fecha_ocurrencia: '2026-03-21',
    fecha_reporte: '2026-03-22',
    monto_reclamado: 4200,
    suma_asegurada: 15000,
    estado: 'Pago Total',
    sucursal: 'Loja',
    vehiculo: { marca: 'Suzuki', modelo: 'Vitara', anio: 2018, placa: 'LBN-3091' },
    proveedor: 'PRV-0204',
    descripcion: 'Daños a tercero en estacionamiento. Tercer evento solo RC en 16 meses.',
    score: 47,
    alertas: [
      {
        code: 'AF01',
        puntos: 6,
        severidad: 'med',
        detalle: '3 eventos previos de solo RC en 16 meses.',
      },
      { code: 'AF04', puntos: 3, severidad: 'low', detalle: 'Monto reclamado dentro de rango.' },
    ],
    timeline: [
      { date: '2024-11-10', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2025-04-22', title: 'RC previa (1)', tone: 'warn' },
      { date: '2025-09-15', title: 'RC previa (2)', tone: 'warn' },
      { date: '2026-03-21', title: 'RC actual', tone: 'warn' },
    ],
    documentos: [
      { tipo: 'Solicitud', estado: 'Completo' },
      { tipo: 'Parte policial', estado: 'Completo' },
      { tipo: 'Carta de tercero', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08233',
    ramo: 'hogar',
    cobertura: 'Robo de contenido',
    asegurado: 'Daniela P. Espinoza C.',
    asegurado_id: 'ASG-33422',
    poliza: 'PH-7782010',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-03-18',
    fecha_reporte: '2026-03-19',
    monto_reclamado: 6100,
    suma_asegurada: 8000,
    estado: 'Reserva',
    sucursal: 'Quito Norte',
    proveedor: null,
    descripcion:
      'Robo de contenido en domicilio. Monto reclamado representa 76% de suma asegurada.',
    score: 68,
    alertas: [
      { code: 'AF04', puntos: 5, severidad: 'med', detalle: 'Reclamo 76% de la suma asegurada.' },
      {
        code: 'AF02',
        puntos: 4,
        severidad: 'med',
        detalle: 'Faltan facturas de bienes sustraídos (>$2,000).',
      },
      {
        code: 'RF02',
        puntos: 10,
        severidad: 'high',
        detalle: 'Una factura presentada tiene fecha posterior al evento.',
      },
    ],
    timeline: [
      { date: '2025-05-18', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-03-18', title: 'Robo reportado', tone: 'warn' },
      { date: '2026-03-19', title: 'Reporte de siniestro', tone: 'ok' },
      {
        date: '2026-03-25',
        title: 'Revisión documental',
        tone: 'danger',
        desc: 'Factura con fecha inconsistente.',
      },
    ],
    documentos: [
      { tipo: 'Solicitud', estado: 'Completo' },
      { tipo: 'Denuncia fiscal', estado: 'Completo' },
      { tipo: 'Facturas de bienes', estado: 'Inconsistente', falta: true },
      { tipo: 'Fotografías', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08218',
    ramo: 'vida',
    cobertura: 'Indemnización por accidente',
    asegurado: 'Ricardo H. Solórzano',
    asegurado_id: 'ASG-90091',
    poliza: 'PV-4419821',
    ciudad: 'Manta',
    fecha_ocurrencia: '2026-03-12',
    fecha_reporte: '2026-03-14',
    monto_reclamado: 12000,
    suma_asegurada: 50000,
    estado: 'Reserva',
    sucursal: 'Manta',
    proveedor: null,
    descripcion: 'Indemnización por accidente laboral con incapacidad temporal. Caso estándar.',
    score: 22,
    alertas: [
      { code: 'AF02', puntos: 2, severidad: 'low', detalle: 'Falta certificado del IESS.' },
    ],
    timeline: [
      { date: '2024-08-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-03-12', title: 'Accidente laboral', tone: 'ok' },
      { date: '2026-03-14', title: 'Reporte', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Certificado médico', estado: 'Completo' },
      { tipo: 'Certificado IESS', estado: 'Faltante', falta: true },
      { tipo: 'Informe del empleador', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08197',
    ramo: 'vehiculos',
    cobertura: 'Choque múltiple',
    asegurado: 'Mateo J. Ríos B.',
    asegurado_id: 'ASG-11091',
    poliza: 'PV-5588111',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-03-05',
    fecha_reporte: '2026-03-06',
    monto_reclamado: 8800,
    suma_asegurada: 24000,
    estado: 'Pago Total',
    sucursal: 'Quito Centro',
    vehiculo: { marca: 'Renault', modelo: 'Duster', anio: 2022, placa: 'PCJ-2199' },
    proveedor: 'PRV-0512',
    descripcion: 'Colisión múltiple en vía interbarrial. Documentación completa.',
    score: 28,
    alertas: [
      { code: 'AF05', puntos: 0, severidad: 'low', detalle: 'Tercero identificado, caso normal.' },
    ],
    timeline: [
      { date: '2025-07-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-03-05', title: 'Choque múltiple', tone: 'ok' },
      { date: '2026-03-06', title: 'Reporte', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Parte policial', estado: 'Completo' },
      { tipo: 'Proforma', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08181',
    ramo: 'vehiculos',
    cobertura: 'Daños propios',
    asegurado: 'Verónica I. Castro L.',
    asegurado_id: 'ASG-77881',
    poliza: 'PV-2298811',
    ciudad: 'Guayaquil',
    fecha_ocurrencia: '2026-02-28',
    fecha_reporte: '2026-03-01',
    monto_reclamado: 7600,
    suma_asegurada: 18000,
    estado: 'Pago Parcial',
    sucursal: 'Guayaquil Sur',
    vehiculo: { marca: 'Nissan', modelo: 'Sentra', anio: 2020, placa: 'GBJ-4471' },
    proveedor: 'PRV-0317',
    descripcion: 'Daños por colisión con elemento fijo. Documentación adecuada.',
    score: 34,
    alertas: [
      {
        code: 'AF02',
        puntos: 2,
        severidad: 'low',
        detalle: 'Falta certificado de licencia vigente.',
      },
    ],
    timeline: [
      { date: '2025-09-12', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-02-28', title: 'Daño reportado', tone: 'ok' },
      { date: '2026-03-01', title: 'Reporte', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Parte policial', estado: 'Completo' },
      { tipo: 'Licencia vigente', estado: 'Faltante', falta: true },
    ],
  },
  {
    id: 'SIN-2026-08164',
    ramo: 'salud',
    cobertura: 'Consulta especializada',
    asegurado: 'Tomás L. Aguilar N.',
    asegurado_id: 'ASG-58812',
    poliza: 'PS-1129922',
    ciudad: 'Cuenca',
    fecha_ocurrencia: '2026-02-22',
    fecha_reporte: '2026-02-22',
    monto_reclamado: 420,
    suma_asegurada: 15000,
    estado: 'Liquidado',
    sucursal: 'Cuenca',
    proveedor: 'PRV-0078',
    descripcion: 'Consulta médica especializada. Caso estándar.',
    score: 8,
    alertas: [],
    timeline: [
      { date: '2025-11-01', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-02-22', title: 'Consulta médica', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Factura', estado: 'Completo' },
      { tipo: 'Receta', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08143',
    ramo: 'vehiculos',
    cobertura: 'Robo de accesorios',
    asegurado: 'Patricia L. Vélez H.',
    asegurado_id: 'ASG-11290',
    poliza: 'PV-7732001',
    ciudad: 'Machala',
    fecha_ocurrencia: '2026-02-15',
    fecha_reporte: '2026-02-19',
    monto_reclamado: 1900,
    suma_asegurada: 16000,
    estado: 'Reserva',
    sucursal: 'Machala',
    vehiculo: { marca: 'Toyota', modelo: 'RAV4', anio: 2021, placa: 'OBA-3318' },
    proveedor: 'PRV-0204',
    descripcion: 'Hurto de accesorios. Reporte 4 días después del evento.',
    score: 44,
    alertas: [
      { code: 'AF03', puntos: 3, severidad: 'med', detalle: 'Reporte 4 días después.' },
      {
        code: 'AF02',
        puntos: 4,
        severidad: 'low',
        detalle: 'Faltan facturas de accesorios reclamados.',
      },
    ],
    timeline: [
      { date: '2025-10-20', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-02-15', title: 'Hurto', tone: 'ok' },
      { date: '2026-02-19', title: 'Reporte', tone: 'warn' },
    ],
    documentos: [
      { tipo: 'Denuncia', estado: 'Completo' },
      { tipo: 'Facturas accesorios', estado: 'Faltante', falta: true },
    ],
  },
  {
    id: 'SIN-2026-08122',
    ramo: 'hogar',
    cobertura: 'Incendio',
    asegurado: 'Felipe A. Cordero S.',
    asegurado_id: 'ASG-22890',
    poliza: 'PH-9920113',
    ciudad: 'Quito',
    fecha_ocurrencia: '2026-02-08',
    fecha_reporte: '2026-02-08',
    monto_reclamado: 23400,
    suma_asegurada: 35000,
    estado: 'Pago Total',
    sucursal: 'Quito Norte',
    proveedor: null,
    descripcion: 'Incendio en cocina por falla eléctrica. Caso bien documentado.',
    score: 26,
    alertas: [
      {
        code: 'AF04',
        puntos: 3,
        severidad: 'low',
        detalle: 'Reclamo 67% de la suma asegurada (esperado para incendios).',
      },
    ],
    timeline: [
      { date: '2024-12-15', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-02-08', title: 'Incendio', tone: 'ok' },
      { date: '2026-02-08', title: 'Reporte inmediato', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Informe de bomberos', estado: 'Completo' },
      { tipo: 'Informe pericial', estado: 'Completo' },
      { tipo: 'Fotografías', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08101',
    ramo: 'vehiculos',
    cobertura: 'Pérdida total por choque',
    asegurado: 'Esteban R. Quirola B.',
    asegurado_id: 'ASG-77110',
    poliza: 'PV-3399112',
    ciudad: 'Riobamba',
    fecha_ocurrencia: '2026-02-02',
    fecha_reporte: '2026-02-03',
    monto_reclamado: 21500,
    suma_asegurada: 22000,
    estado: 'Reserva',
    sucursal: 'Riobamba',
    vehiculo: { marca: 'Kia', modelo: 'Picanto', anio: 2017, placa: 'HBA-9920' },
    proveedor: 'PRV-0142',
    descripcion:
      'Pérdida total por choque. Taller asignado en lista restrictiva. Asegurado con segundo siniestro en 14 meses.',
    score: 81,
    alertas: [
      {
        code: 'RF03',
        puntos: 10,
        severidad: 'high',
        detalle: 'Taller PRV-0142 en lista restrictiva.',
      },
      { code: 'AF04', puntos: 5, severidad: 'high', detalle: 'Reclamo 98% de la suma asegurada.' },
      { code: 'AF01', puntos: 4, severidad: 'med', detalle: 'Segundo siniestro en 14 meses.' },
    ],
    timeline: [
      { date: '2025-04-15', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2025-12-08', title: 'Siniestro previo (SIN-2025-07712)', tone: 'warn' },
      { date: '2026-02-02', title: 'Pérdida total', tone: 'danger' },
      { date: '2026-02-09', title: 'Asignación a taller en lista restrictiva', tone: 'danger' },
    ],
    documentos: [
      { tipo: 'Parte policial', estado: 'Completo' },
      { tipo: 'Proforma', estado: 'Completo' },
      { tipo: 'Matrícula', estado: 'Completo' },
    ],
  },
  {
    id: 'SIN-2026-08087',
    ramo: 'salud',
    cobertura: 'Hospitalización',
    asegurado: 'Camila M. Yánez T.',
    asegurado_id: 'ASG-66109',
    poliza: 'PS-1198829',
    ciudad: 'Guayaquil',
    fecha_ocurrencia: '2026-01-28',
    fecha_reporte: '2026-01-28',
    monto_reclamado: 5680,
    suma_asegurada: 30000,
    estado: 'Liquidado',
    sucursal: 'Guayaquil Centro',
    proveedor: 'PRV-0089',
    descripcion: 'Hospitalización por neumonía. Documentación clínica completa.',
    score: 16,
    alertas: [],
    timeline: [
      { date: '2025-04-10', title: 'Inicio de vigencia', tone: 'ok' },
      { date: '2026-01-28', title: 'Hospitalización', tone: 'ok' },
    ],
    documentos: [
      { tipo: 'Epicrisis', estado: 'Completo' },
      { tipo: 'Factura', estado: 'Completo' },
    ],
  },
];

import type { ClaimReview } from '../models/claim-review.model';

function synthReview(index: number, claimId: string): ClaimReview {
  // Deterministic mockup review state, distributed so the demo shows every variant.
  switch (index) {
    case 0:
      // SIN-2026-08412 (score 91) — pendiente: the analista's first action target.
      return { status: 'pendiente', bounce_count: 0 };
    case 1:
      // SIN-2026-08398 (score 87) — escalado: visible in antifraude bandeja, not yet taken.
      return {
        status: 'escalado',
        escalated_by: 'usr_ana',
        escalated_by_name: 'Ana Lema',
        escalated_at: '2026-05-26T09:14:00-05:00',
        escalation_note:
          'Tercer evento con narrativa similar. Sugiero revisión cruzada con SIN-2025-07112 y SIN-2025-07955.',
        bounce_count: 0,
      };
    case 2:
      // Third highest — en_revision: antifraude has taken it.
      return {
        status: 'en_revision',
        escalated_by: 'usr_ana',
        escalated_by_name: 'Ana Lema',
        escalated_at: '2026-05-25T16:02:00-05:00',
        escalation_note: 'Documentación incompleta y proveedor con historial denso.',
        assigned_to: 'usr_lucia',
        assigned_to_name: 'Lucía Vélez',
        taken_at: '2026-05-26T08:42:00-05:00',
        bounce_count: 0,
      };
    case 3:
      // Fourth — dictaminado confirmado_sospecha: shows DictamenCard.
      return {
        status: 'dictaminado',
        escalated_by: 'usr_ana',
        escalated_by_name: 'Ana Lema',
        escalated_at: '2026-05-24T11:20:00-05:00',
        escalation_note: 'Pérdida total cerca del borde de vigencia, taller en lista observada.',
        assigned_to: 'usr_lucia',
        assigned_to_name: 'Lucía Vélez',
        taken_at: '2026-05-24T14:05:00-05:00',
        dictamen_outcome: 'confirmado_sospecha',
        dictamen_justificacion:
          'Cruzando proveedor PRV-0142 con casos previos se observa patrón consistente con simulación. Recomiendo elevar a comité antifraude y solicitar inspección pericial del vehículo previo a cualquier liquidación.',
        dictaminado_by: 'usr_lucia',
        dictaminado_by_name: 'Lucía Vélez',
        dictaminado_at: '2026-05-25T17:48:00-05:00',
        bounce_count: 0,
      };
    case 4:
      // Fifth — pendiente con bounce: shows EscalationStickyBanner.
      return {
        status: 'pendiente',
        bounce_count: 1,
        bounce_note:
          'Falta acta de inspección física del taller y reporte ampliatorio del ajustador. Sin esos documentos no puedo descartar la sospecha — re-escalar una vez adjuntos.',
        escalated_by_name: 'Ana Lema',
        escalated_at: '2026-05-24T08:10:00-05:00',
        assigned_to_name: 'Lucía Vélez',
        dictaminado_by_name: 'Lucía Vélez',
        dictaminado_at: '2026-05-25T10:32:00-05:00',
      };
    default:
      // The rest stay pendiente without bounce — the analista's regular triage queue.
      return { status: 'pendiente', bounce_count: 0 };
  }
}

export const MOCK_CLAIMS: Claim[] = RAW.map((c, i) => ({
  ...c,
  nivel: riskTier(c.score),
  review: synthReview(i, c.id),
}));
