import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

import openapiTS, { astToString } from 'openapi-typescript';

const url = process.env.BACKEND_URL ?? 'http://localhost:8000';
const schemaUrl = new URL('/openapi.json', url);
const outPath = 'src/app/core/api/generated/schema.ts';

console.log(`[gen:api] fetching ${schemaUrl}`);

try {
  const ast = await openapiTS(schemaUrl);
  const contents = astToString(ast);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(
    outPath,
    `/* eslint-disable */\n/* prettier-ignore */\n/* AUTOGENERATED by scripts/gen-api.mjs — do not edit by hand. */\n\n${contents}`,
    'utf8',
  );
  console.log(`[gen:api] wrote ${outPath}`);
} catch (err) {
  console.error(`[gen:api] failed:`, err);
  process.exitCode = 1;
}
